language: python
python:
  - "3.6"
install:
  - .travis/install.sh
script:
  # Disabling flake8 for now, because there are so many thing to fix
#  - flake8
#  - flake8 --config .flake8.cython
  # Ignoring tests that rely on Gurobi, for now
  - py.test tests/ --ignore tests/sol/opt --ignore tests/sol/composition
cache: pip
